name: firebase_ui
description: Firebase auth UI fork for dependencies
version: 0.0.17
author: Nicholas Bowler
homepage: https://github.com/fidelisa/flutter_plugins

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_twitter_login: ^1.1.0

  firebase_auth: ^0.8.4

  google_sign_in: ^4.0.1+3
  flutter_facebook_login: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fb-logo.png
    - assets/2.0x/fb-logo.png
    - assets/3.0x/fb-logo.png

    - assets/email-logo.png
    - assets/2.0x/email-logo.png
    - assets/3.0x/email-logo.png

    - assets/go-logo.png
    - assets/2.0x/go-logo.png
    - assets/3.0x/go-logo.png

    - assets/twitter-logo.png
    - assets/2.0x/twitter-logo.png
    - assets/3.0x/twitter-logo.png
